image: microsoft/dotnet:sdk
pipelines:
  default:
    default:
      -step:
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build
          - dotnet test
        script: # Modify the commands below to build your repository.
          - pipe: microsoft/azure-web-apps-deploy:1.0.2
          variables:
            AZURE_APP_ID: $AZURE_APP_ID
            AZURE_PASSWORD: $AZURE_PASSWORD
            AZURE_TENANT_ID: $AZURE_TENANT_ID
            AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
            AZURE_APP_NAME: '$AZURE_APP_NAME'
            ZIP_FILE: 'harris-$BITBUCKET_BUILD_NUMBER.zip'