// <auto-generated />
using System;
using HarrisPharmacy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HarrisPharmacy.App.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191016221555_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HarrisPharmacy.App.Data.Entities.Forms.Form", b =>
                {
                    b.Property<string>("FormId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("HarrisPharmacy.App.Data.Entities.Forms.FormField", b =>
                {
                    b.Property<string>("FormFieldId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormInputType")
                        .HasColumnType("int");

                    b.Property<bool>("UseValues")
                        .HasColumnType("bit");

                    b.Property<string>("Values")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormFieldId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("HarrisPharmacy.App.Data.Entities.Forms.FormWithFields", b =>
                {
                    b.Property<string>("FormWithFieldsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFieldId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FormId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FormWithFieldsId");

                    b.HasIndex("FormFieldId");

                    b.HasIndex("FormId");

                    b.ToTable("FormWithFields");
                });

            modelBuilder.Entity("HarrisPharmacy.App.Data.Entities.Forms.FormWithFields", b =>
                {
                    b.HasOne("HarrisPharmacy.App.Data.Entities.Forms.FormField", "FormField")
                        .WithMany("FormWithFields")
                        .HasForeignKey("FormFieldId");

                    b.HasOne("HarrisPharmacy.App.Data.Entities.Forms.Form", "Form")
                        .WithMany("FormWithFields")
                        .HasForeignKey("FormId");
                });
#pragma warning restore 612, 618
        }
    }
}
